const en: Record<string, string> = {
  back: "Back",
  required: "Required",
  invalid_format: "Invalid format",
  pick_at_least_one: "Pick at least one",
  must_be_positive: "Must be a positive number",
  must_be_non_negative: "Must be a number >= 0",

  menu_generate_report: "Generate Report",
  menu_projects_config: "Projects Config",
  menu_git_config: "Git Config",
  menu_ai_config: "AI Config",
  menu_help: "Help",
  menu_exit: "Exit",

  projects_settings: "Project Settings",
  projects_list_count: "Project list (edit/delete) ({count})",
  projects_add_update: "Add/Update project",
  projects_scan_import: "Scan directory and import Git projects",
  projects_name: "Project name",
  projects_repo_path: "Local repository path",
  projects_select_one: "Select a project",
  projects_item: "Project: {name}",
  edit: "Edit",
  delete: "Delete",
  back_to_list: "Back to list",
  confirm_delete: "Confirm delete {name}?",
  scan_root: "Scan root directory",
  scan_depth: "Scan depth (default 1 = one level)",
  no_new_git_repos: "No new Git repositories found to import.",
  found_git_repos_pick: "Found {count} Git repositories. Select projects to import.",

  choose_summary_type: "Choose summary type",
  range_daily: "Daily (today 00:00 → now)",
  range_weekly: "Weekly (Mon 00:00 → now)",
  range_monthly: "Monthly (1st 00:00 → now)",
  range_yearly: "Yearly (Jan 1 00:00 → now)",
  range_custom: "Custom (enter start/end dates)",
  start_date: "Start date (YYYY-MM-DD)",
  end_date: "End date (YYYY-MM-DD, blank = today)",
  output_mode: "Output mode",
  output_stdout: "Terminal only",
  output_file: "File only",
  output_both: "Terminal + file",
  export_file_path: "Export file path",
  remember_output_dir: "Remember default output dir as: {dir}?",
  select_projects_multi: "Select projects to include [multi-select]",
  title: "Title",
  only_my_commits: "Only my commits (filter by author)?",
  detected_git_user_choose: "Detected Git user info. Choose one to filter.",
  manual_input: "Manual input (email/name/regex)",
  author_filter: "Author filter (passed to git log --author=...)",
  no_git_user_enter_filter: "No user.email/user.name detected. Enter author filter (email/name/regex)",
  save_as_default_filter: "Save as default filter ({pattern})?",
  use_ai_question: "Use AI to summarize?",
  no_ai_config_use_local: "No AI config detected. Use local summary?",
  configure_ai_now: "Configure AI now? (After configuring, AI will be used; otherwise continue locally)",

  git_settings: "Git Settings (author filter: {filter})",
  git_set_filter: "Set author filter (only me)",
  git_clear_filter: "Clear author filter (everyone)",
  choose_author_id: "Choose an author identifier",
  no_git_user_manual: "No user.email/user.name detected, enter manually",

  ai_settings: "AI Settings",
  ai_configure_endpoint: "Configure Key / Endpoint",
  ai_configure_prompt: "Configure Prompt",
  ai_configure_skills: "Configure Skills",
  ai_clear_key: "Clear API Key",
  ai_api_key: "AI_API_KEY",
  ai_update_key: "apiKey exists ({masked}). Update?",
  ai_api_key_update: "AI_API_KEY (update)",
  ai_base_url: "AI_BASE_URL",
  ai_model: "AI_MODEL",
  ai_timeout_ms: "AI_TIMEOUT_MS (ms)",
  ai_enable_stream: "Enable streaming output to console (stream)?",
  prompt_select: "Select prompt",
  prompt_custom_path: "Custom prompt file path (txt/md)",
  skills_path_optional: "Skills file path (optional, blank = none)",
  continue_config_prompt_skills: "Continue configuring Prompt / Skills?",
  builtin_prefix: "Built-in",
  custom_from_file: "Custom: load from file",
};

export default en;
