const zh: Record<string, string> = {
  back: "返回",
  required: "必填",
  invalid_format: "格式不对",
  pick_at_least_one: "至少选一个",
  must_be_positive: "必须是正数",
  must_be_non_negative: "必须是 >= 0 的数字",

  menu_generate_report: "选择项目生成报告",
  menu_projects_config: "项目配置",
  menu_git_config: "Git 配置",
  menu_ai_config: "AI 配置",
  menu_help: "帮助",
  menu_exit: "退出",

  projects_settings: "项目配置",
  projects_list_count: "项目列表（选择编辑/删除）（{count}）",
  projects_add_update: "添加/更新项目",
  projects_scan_import: "扫描目录并自动导入 git 项目",
  projects_name: "项目名",
  projects_repo_path: "本地仓库路径",
  projects_select_one: "选择一个项目",
  projects_item: "项目：{name}",
  edit: "编辑",
  delete: "删除",
  back_to_list: "返回列表",
  confirm_delete: "确认删除 {name}？",
  scan_root: "扫描目录（root）",
  scan_depth: "扫描深度（默认 1=只扫一层子目录）",
  no_new_git_repos: "未发现可导入的新 git 仓库。",
  found_git_repos_pick: "发现 {count} 个 git 仓库，选择要导入的项目",

  choose_summary_type: "选择摘要类型",
  range_daily: "日报（今天 00:00 至今）",
  range_weekly: "周报（本周一 00:00 至今）",
  range_monthly: "月报（本月 1 号 00:00 至今）",
  range_yearly: "年报（今年 1 月 1 号 00:00 至今）",
  range_custom: "自定义（输入起止日期）",
  start_date: "开始日期（YYYY-MM-DD）",
  end_date: "结束日期（YYYY-MM-DD，可留空=今天）",
  output_mode: "输出方式",
  output_stdout: "仅终端显示",
  output_file: "仅导出文件",
  output_both: "终端 + 文件",
  export_file_path: "导出文件路径",
  remember_output_dir: "记住默认输出目录为：{dir}？",
  select_projects_multi: "选择要生成摘要的项目[可多选]",
  title: "标题",
  only_my_commits: "只统计我的提交（按作者过滤）？",
  detected_git_user_choose: "检测到 git 用户信息，选择一个用来过滤",
  manual_input: "手动输入（邮箱/姓名/正则）",
  author_filter: "提交人过滤（传给 git log --author=...）",
  no_git_user_enter_filter: "未检测到 user.email/user.name，请输入提交人过滤（邮箱/姓名/正则）",
  save_as_default_filter: "保存为默认过滤（{pattern}）？",
  use_ai_question: "使用 AI 进行归纳整理？",
  no_ai_config_use_local: "未检测到 AI 配置，使用本地整理？",
  configure_ai_now: "现在配置 AI？（配置后会使用 AI，否则继续本地整理）",

  git_settings: "Git 配置（提交人过滤：{filter}）",
  git_set_filter: "设置提交人过滤（只看自己）",
  git_clear_filter: "清空提交人过滤（看全员）",
  choose_author_id: "选择一个提交人标识",
  no_git_user_manual: "未检测到 user.email/user.name，手动输入",

  ai_settings: "AI 配置",
  ai_configure_endpoint: "配置 Key / Endpoint",
  ai_configure_prompt: "配置 Prompt",
  ai_configure_skills: "配置 Skills",
  ai_clear_key: "清空 API Key",
  ai_api_key: "AI_API_KEY",
  ai_update_key: "已存在 apiKey（{masked}），需要更新吗？",
  ai_api_key_update: "AI_API_KEY（更新）",
  ai_base_url: "AI_BASE_URL",
  ai_model: "AI_MODEL",
  ai_timeout_ms: "AI_TIMEOUT_MS（毫秒）",
  ai_enable_stream: "启用流式输出到控制台（stream）？",
  prompt_select: "Prompt 选择",
  prompt_custom_path: "自定义 Prompt 文件路径（txt/md 均可）",
  skills_path_optional: "Skills 文件路径（可选，留空=不注入）",
  continue_config_prompt_skills: "继续配置 Prompt / Skills？",
  builtin_prefix: "内置",
  custom_from_file: "自定义：从文件加载",
};

export default zh;
